-- Future migration reference. Do not run until a Supabase project is approved.
create table if not exists public.admin_users (id uuid primary key default gen_random_uuid(), username text unique not null, role text not null check (role in ('SuperAdmin','Admin','Operator')), enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.membership_plans (id text primary key, name text not null, duration_days integer, price numeric(12,2) not null default 0, original_price numeric(12,2), benefits jsonb not null default '[]', enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.redeem_code_batches (id uuid primary key default gen_random_uuid(), type text not null, value jsonb not null, quantity integer not null, created_by uuid, source text, remark text, order_reference text, created_at timestamptz not null default now());
create table if not exists public.redeem_codes (id uuid primary key default gen_random_uuid(), code_hash text unique not null, batch_id uuid references public.redeem_code_batches(id), type text not null, value jsonb not null, status text not null default 'unused' check (status in ('unused','used','expired','revoked')), expires_at timestamptz, used_at timestamptz, used_by uuid, created_by uuid, revoked_at timestamptz, revoked_by uuid, created_at timestamptz not null default now());
create table if not exists public.memberships (id uuid primary key default gen_random_uuid(), user_id uuid not null, plan_id text references public.membership_plans(id), start_at timestamptz not null, end_at timestamptz, source text, order_id uuid, redeem_code_id uuid references public.redeem_codes(id), status text not null default 'active', created_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), user_id uuid, product_id text, amount numeric(12,2) not null default 0, currency text not null default 'CNY', status text not null default 'pending', payment_channel text, payment_reference text, metadata jsonb not null default '{}', created_at timestamptz not null default now(), paid_at timestamptz, cancelled_at timestamptz);
create table if not exists public.admin_operation_logs (id uuid primary key default gen_random_uuid(), admin_id uuid, action text not null, target_type text, target_id text, before_data jsonb, after_data jsonb, ip_masked text, user_agent text, created_at timestamptz not null default now());
alter table public.admin_users enable row level security; alter table public.redeem_codes enable row level security; alter table public.memberships enable row level security; alter table public.orders enable row level security; alter table public.admin_operation_logs enable row level security;
-- All admin writes and redeem transactions must use server-side Edge Functions with service role; never expose service role to the browser.
